spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///easydb?useUnicode=true&useSSL=false
    username: root
    password: root
    druid:
      max-active: 50
      initial-size: 5
      min-idle: 5

mybatis:
  type-aliases-package: cn.cy.resources.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false