server:
  port: 11000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aevlp/easymall-config
#          username:
#          password:
      label: master
#          search-paths: /config,....
